### ISSUE TITLE
Register as pool service company - service type

### ISSUE THREAD

**Issue by christa23** [Rowboatllc/poolservice#14]
I should be able to choose all options when on this page:
![screen shot 2017-05-18 at 12 56 57 pm](https://cloud.githubusercontent.com/assets/11478530/26220957/a78537c6-3bc9-11e7-84fb-b93fbc5e1750.png)

**Comment by maiquynh** [comment]
@christa23 With the circle tick (salt water, chlorine), it means we let people choose either kind only (it's understood same way in many other platforms), if you want to choose all options, we need to change that to square. How do you think?

**Comment by christa23** [comment]
For pool service company, they should be able to check all boxes.
For pool service customer, they should be able to check both Pool and Spa; and either chlorine or saltwater.

**Comment by sancao** [comment]
@christa23 , i just fixed it, could you review it, pls tell me if you find out any issues.
